format_version: 3
pipelines:
  "do-it":
    group: SRE
    locking: off
    materials:
      git:
        git: "https://github.com/fakarakas/some-scripts.git"
        auto_update: false
    stages:
      - "pre-stage":
          clean_workspace: true
          approval:
            type: success
            roles:
              - SRE
          jobs:
            sql-dump:
              elastic_profile_id: "demo-app"
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - "-c"
                      - "sleep 5000"
